"use client";

import {
  createContext,
  ReactNode,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";

export const LANGUAGES = ["uz", "ru", "en"] as const;
export type Language = (typeof LANGUAGES)[number];

const dictionaries = {
  uz: {
    brand: "Aura AI",
    secureAccess: "Xavfsiz kirish",
    heroTitle: "Aqlli hayot qarorlari xotirjam moliyaviy aniqlikdan boshlanadi.",
    heroBody:
      "Kundalik xarajatlar, jamg'arma maqsadlari va AI tavsiyalari bitta qulay ish maydonida jamlangan.",
    monthlyOverview: "Oylik ko'rinish",
    cashFlow: "AI kuzatayotgan pul oqimi",
    savingsStreak: "Jamg'arma seriyasi",
    steadyProgress: "Barqaror o'sish, kamroq stress",
    signupTitle: "Akkauntingizni yarating",
    signupSubtitle:
      "Budjetlar, maqsadlar va kelajakdagi AI moliyaviy insightlari uchun xavfsiz ish maydoni yarating.",
    signupFooter: "Akkauntingiz bormi?",
    signIn: "Kirish",
    loginTitle: "Yana bir bor xush kelibsiz",
    loginSubtitle:
      "Xarajat ritmini, maqsadlar bo'yicha progressni va AI tavsiyalarini ko'rish uchun tizimga kiring.",
    loginFooter: "Aura AI’da yangimisiz?",
    createAccount: "Akkaunt yaratish",
    fullName: "To'liq ism",
    email: "Email",
    password: "Parol",
    passwordHint: "Kamida 8 ta belgi",
    nameRequired: "Ism kiritilishi shart",
    nameMin: "Ism kamida 2 ta belgidan iborat bo'lsin",
    emailRequired: "Email kiritilishi shart",
    emailInvalid: "Email formati noto'g'ri",
    passwordRequired: "Parol kiritilishi shart",
    passwordMin: "Parol kamida 8 ta belgidan iborat bo'lsin",
    signupSuccess: "Akkaunt yaratildi. Endi dashboard tayyor.",
    signupError: "Ro'yxatdan o'tib bo'lmadi",
    signupCreating: "Akkaunt yaratilmoqda...",
    signupSubmit: "Akkaunt yaratish",
    loginSuccess: "Xush kelibsiz. Sessiya muvaffaqiyatli ochildi.",
    loginError: "Kirish amalga oshmadi",
    loginCreating: "Kirilmoqda...",
    loginSubmit: "Kirish",
    dashboardTitle: "Aura AI Dashboard",
    dashboardGreeting: "Salom, {name}. Xarajatlaringizni yozib boring, qolganini AI kuzatadi.",
    dashboardGreetingFallback: "do'stim",
    dashboardSubtitle:
      "Oddiy gap bilan xarajat kiriting, maqsad yarating va trendlarni bitta interaktiv maydonda kuzating.",
    refresh: "Yangilash",
    logout: "Chiqish",
    dashboardLoadError: "Dashboard yuklanmadi",
    insight: "Zukko AI maslahat",
    insightLoading: "Insight tayyorlanmoqda",
    insightBody:
      "Dashboard ochilishi bilan AI xarajat trendlaringizni tahlil qilib shu yerda qisqa maslahat beradi.",
    totalIncome: "Jami daromad",
    totalIncomeBody: "Kiritilgan barcha daromadlar yig'indisi.",
    totalSpent: "Jami xarajat",
    totalSpentBody: "Barcha yozilgan xarajatlar yig'indisi",
    netBalance: "Sof balans",
    netBalanceBody: "Daromad va xarajatlar orasidagi farq",
    thisMonth: "Shu oy",
    thisMonthBody: "Joriy oy sarfi va momentum ko'rinishi",
    activeGoals: "Faol maqsadlar",
    activeGoalsBody: "Jamg'arma maqsadlari soni",
    expenseParser: "Xarajat parseri",
    expenseParserTitle: "Xarajatni shunchaki yozib yuboring",
    cashflowEntry: "Qo'lda kiritish",
    cashflowEntryTitle: "Daromad yoki xarajatni tez qo'shing",
    cashflowEntryBody:
      "Daromadni alohida yashil oqimda, qo'lda kiritilgan xarajatni esa boshqariladigan formatda saqlang.",
    aiVisibility: "AI kuzatuvi",
    aiVisibilityTitle: "Har refresh yangi kuzatuv",
    aiVisibilityBody:
      "Dashboard qayta ochilganda AI so'nggi xarajatlar va maqsad holatiga qarab yangi signal ishlab chiqaradi.",
    currentSignal: "Joriy signal",
    aiCollecting: "AI hali ma'lumot yig'moqda.",
    spendingTrend: "Xarajat trendi",
    spendingTrendTitle: "So'nggi 7 kun dinamikasi",
    spendingTrendEmpty: "Trend chiqishi uchun kamida bitta xarajat qo'shing",
    categoryMix: "Kategoriya aralashmasi",
    categoryMixTitle: "Pul qayerga ketmoqda",
    categoryMixEmpty: "Kategoriyalar AI parserdan keyin shu yerda paydo bo'ladi",
    newGoal: "Yangi maqsad",
    newGoalTitle: "Jamg'arma maqsadi yarating",
    goalTracker: "Maqsad kuzatuvi",
    goalTrackerTitle: "Qancha qolganini ko'ring",
    goalRemaining: "Qoldi: {amount}",
    saved: "Jamg'arilgan: {amount}",
    target: "Maqsad: {amount}",
    noGoals: "Hali maqsad yo'q. Masalan, \"Mashina uchun 100 000 000\" kabi maqsad qo'shing.",
    recentActivity: "So'nggi faollik",
    recentActivityTitle: "So'nggi kirim va chiqimlar",
    noTransactions: "Yuqoridan birinchi daromad yoki xarajatni kiriting.",
    session: "Sessiya",
    sessionTitle: "Joriy foydalanuvchi",
    name: "Ism",
    status: "Holat",
    refreshing: "Dashboard yangilanmoqda",
    workspace: "AI bilan bog'langan ish maydoni",
    goalRequired: "Maqsad nomi va target amount kiritilishi shart.",
    goalTargetPositive: "Target amount 0 dan katta bo'lishi kerak.",
    goalCurrentPositive: "Current saved manfiy bo'lishi mumkin emas.",
    goalSuccess: "Yangi maqsad qo'shildi.",
    goalPlaceholder: "Masalan: Mashina uchun jamg'arma",
    goalTargetPlaceholder: "Maqsad summasi",
    goalCurrentPlaceholder: "Hozir yig'ilgan",
    goalSubmitting: "Saqlanmoqda...",
    goalSubmit: "Maqsad qo'shish",
    goalHint: "Yangi maqsad yaratish yoki mavjud maqsadga qo'shish rejimini tanlang.",
    createGoalMode: "Yangi maqsad",
    contributeGoalMode: "Mavjudiga qo'shish",
    selectGoal: "Maqsadni tanlang",
    contributeAmount: "Qo'shiladigan summa",
    contributeSubmit: "Maqsadga qo'shish",
    contributeSuccess: "Maqsadga summa qo'shildi.",
    goalSelectRequired: "Avval mavjud maqsadni tanlang.",
    goalUpdateSuccess: "Maqsad yangilandi.",
    goalDeleteSuccess: "Maqsad o'chirildi.",
    goalUpdateError: "Maqsadni yangilab bo'lmadi",
    goalDeleteError: "Maqsadni o'chirib bo'lmadi",
    expenseEmpty: "Xarajat matnini bo'sh qoldirmang.",
    expenseShort: "Iltimos, xarajat haqida biroz batafsilroq yozing.",
    expenseSuccess: "Xarajat muvaffaqiyatli saqlandi.",
    incomeSuccess: "Daromad muvaffaqiyatli saqlandi.",
    expensePlaceholder:
      "Masalan: Bugun tushlik uchun 65 ming, keyin taxi uchun 18 ming sarfladim",
    expenseSubmitting: "AI tahlil qilmoqda...",
    expenseSubmit: "Xarajatni yozib saqlash",
    cashflowRequired: "Nom, kategoriya va summa kiritilishi shart.",
    cashflowAmountPositive: "Summa 0 dan katta bo'lishi kerak.",
    cashflowSubmitting: "Saqlanmoqda...",
    cashflowCreateError: "Daromad yoki xarajatni saqlab bo'lmadi",
    incomeMode: "Daromad",
    expenseMode: "Xarajat",
    incomeHint: "Oylik, bonus yoki freelance kabi kirimlarni alohida qayd qilib boring.",
    manualExpenseHint: "Qo'lda kiritilgan xarajatlar ham keyin tahrirlanadi va statistikaga qo'shiladi.",
    incomeTitlePlaceholder: "Masalan: Oylik tushdi",
    expenseTitlePlaceholder: "Masalan: Telefon uchun to'lov",
    incomeSubmit: "Daromadni saqlash",
    manualExpenseSubmit: "Qo'lda xarajat qo'shish",
    edit: "Tahrirlash",
    delete: "O'chirish",
    cancel: "Bekor qilish",
    save: "Saqlash",
    deleteSuccess: "Xarajat o'chirildi.",
    updateSuccess: "Xarajat yangilandi.",
    incomeUpdateSuccess: "Daromad yangilandi.",
    incomeDeleteSuccess: "Daromad o'chirildi.",
    transactionTitle: "Xarajat nomi",
    transactionType: "Turi",
    transactionCategory: "Kategoriya",
    transactionAmount: "Summa",
    transactionDate: "Sana",
    transactionNotes: "Izoh",
    transactionUpdateError: "Xarajatni yangilab bo'lmadi",
    transactionDeleteError: "Xarajatni o'chirib bo'lmadi",
  },
  ru: {
    brand: "Aura AI",
    secureAccess: "Безопасный доступ",
    heroTitle: "Умные жизненные решения начинаются со спокойной финансовой ясности.",
    heroBody:
      "Ежедневные траты, цели по сбережениям и AI-подсказки собраны в одном удобном рабочем пространстве.",
    monthlyOverview: "Обзор месяца",
    cashFlow: "Денежный поток под контролем AI",
    savingsStreak: "Серия накоплений",
    steadyProgress: "Стабильный прогресс, меньше стресса",
    signupTitle: "Создайте аккаунт",
    signupSubtitle:
      "Настройте безопасное пространство для бюджетов, целей и будущих AI-финансовых инсайтов.",
    signupFooter: "Уже есть аккаунт?",
    signIn: "Войти",
    loginTitle: "С возвращением",
    loginSubtitle:
      "Войдите, чтобы посмотреть ритм расходов, прогресс по целям и следующие шаги от AI.",
    loginFooter: "Вы впервые в Aura AI?",
    createAccount: "Создать аккаунт",
    fullName: "Полное имя",
    email: "Email",
    password: "Пароль",
    passwordHint: "Минимум 8 символов",
    nameRequired: "Введите имя",
    nameMin: "Имя должно содержать минимум 2 символа",
    emailRequired: "Введите email",
    emailInvalid: "Неверный формат email",
    passwordRequired: "Введите пароль",
    passwordMin: "Пароль должен содержать минимум 8 символов",
    signupSuccess: "Аккаунт создан. Дашборд готов.",
    signupError: "Не удалось зарегистрироваться",
    signupCreating: "Создание аккаунта...",
    signupSubmit: "Создать аккаунт",
    loginSuccess: "Добро пожаловать. Сессия успешно открыта.",
    loginError: "Не удалось войти",
    loginCreating: "Вход...",
    loginSubmit: "Войти",
    dashboardTitle: "Панель Aura AI",
    dashboardGreeting: "Здравствуйте, {name}. Записывайте расходы, остальное отследит AI.",
    dashboardGreetingFallback: "друг",
    dashboardSubtitle:
      "Добавляйте расходы обычным текстом, создавайте цели и следите за трендами в одном интерактивном окне.",
    refresh: "Обновить",
    logout: "Выйти",
    dashboardLoadError: "Не удалось загрузить дашборд",
    insight: "AI-инсайт",
    insightLoading: "Инсайт подготавливается",
    insightBody:
      "Когда вы открываете дашборд, AI анализирует тренды расходов и показывает здесь краткую подсказку.",
    totalIncome: "Total income",
    totalIncomeBody: "Combined total of all recorded income.",
    totalSpent: "Всего расходов",
    totalSpentBody: "Сумма всех записанных расходов",
    netBalance: "Net balance",
    netBalanceBody: "Difference between income and expenses",
    thisMonth: "Этот месяц",
    thisMonthBody: "Расходы текущего месяца и общая динамика",
    activeGoals: "Активные цели",
    activeGoalsBody: "Количество целей по накоплениям",
    expenseParser: "Парсер расходов",
    expenseParserTitle: "Просто опишите расход",
    cashflowEntry: "Manual entry",
    cashflowEntryTitle: "Add income or expense quickly",
    cashflowEntryBody: "Record income in a green flow and keep manual expenses structured and editable.",
    aiVisibility: "Видимость AI",
    aiVisibilityTitle: "Каждое обновление дает новый взгляд",
    aiVisibilityBody:
      "При повторном открытии дашборда AI формирует новый сигнал по последним расходам и состоянию целей.",
    currentSignal: "Текущий сигнал",
    aiCollecting: "AI пока собирает данные.",
    spendingTrend: "Тренд расходов",
    spendingTrendTitle: "Динамика за последние 7 дней",
    spendingTrendEmpty: "Добавьте хотя бы один расход, чтобы увидеть тренд",
    categoryMix: "Категории",
    categoryMixTitle: "Куда уходят деньги",
    categoryMixEmpty: "Категории появятся здесь после обработки AI parser",
    newGoal: "Новая цель",
    newGoalTitle: "Создайте цель накоплений",
    goalTracker: "Трекер целей",
    goalTrackerTitle: "Смотрите, сколько осталось",
    goalRemaining: "Осталось: {amount}",
    saved: "Накоплено: {amount}",
    target: "Цель: {amount}",
    noGoals: "Пока нет целей. Например, добавьте цель вроде «Машина за 100 000 000».",
    recentActivity: "Последняя активность",
    recentActivityTitle: "Recent income and expenses",
    noTransactions: "Add your first income or expense above.",
    session: "Сессия",
    sessionTitle: "Текущий пользователь",
    name: "Имя",
    status: "Статус",
    refreshing: "Дашборд обновляется",
    workspace: "Рабочее пространство с AI",
    goalRequired: "Нужно указать название цели и target amount.",
    goalTargetPositive: "Target amount должен быть больше 0.",
    goalCurrentPositive: "Current saved не может быть отрицательным.",
    goalSuccess: "Новая цель добавлена.",
    goalPlaceholder: "Например: Накопить на машину",
    goalTargetPlaceholder: "Целевая сумма",
    goalCurrentPlaceholder: "Уже накоплено",
    goalSubmitting: "Сохранение...",
    goalSubmit: "Добавить цель",
    goalHint: "Выберите режим: создать новую цель или добавить сумму к существующей.",
    createGoalMode: "Новая цель",
    contributeGoalMode: "Добавить к цели",
    selectGoal: "Выберите цель",
    contributeAmount: "Сумма пополнения",
    contributeSubmit: "Добавить к цели",
    contributeSuccess: "Сумма добавлена к цели.",
    goalSelectRequired: "Сначала выберите существующую цель.",
    goalUpdateSuccess: "Цель обновлена.",
    goalDeleteSuccess: "Цель удалена.",
    goalUpdateError: "Не удалось обновить цель",
    goalDeleteError: "Не удалось удалить цель",
    expenseEmpty: "Не оставляйте поле расхода пустым.",
    expenseShort: "Пожалуйста, опишите расход немного подробнее.",
    expenseSuccess: "Расход успешно сохранен.",
    incomeSuccess: "Income saved successfully.",
    expensePlaceholder:
      "Например: Сегодня на обед ушло 65 тысяч, потом на такси еще 18 тысяч",
    expenseSubmitting: "AI анализирует...",
    expenseSubmit: "Сохранить расход",
    cashflowRequired: "Title, category and amount are required.",
    cashflowAmountPositive: "Amount must be greater than 0.",
    cashflowSubmitting: "Saving...",
    cashflowCreateError: "Could not save the income or expense",
    incomeMode: "Income",
    expenseMode: "Expense",
    incomeHint: "Track salary, bonus and freelance income separately.",
    manualExpenseHint: "Manual expenses stay editable and feed the dashboard stats too.",
    incomeTitlePlaceholder: "For example: Salary arrived",
    expenseTitlePlaceholder: "For example: Phone payment",
    incomeSubmit: "Save income",
    manualExpenseSubmit: "Add manual expense",
    edit: "Изменить",
    delete: "Удалить",
    cancel: "Отмена",
    save: "Сохранить",
    deleteSuccess: "Расход удален.",
    updateSuccess: "Расход обновлен.",
    incomeUpdateSuccess: "Income updated.",
    incomeDeleteSuccess: "Income deleted.",
    transactionTitle: "Название",
    transactionType: "Type",
    transactionCategory: "Категория",
    transactionAmount: "Сумма",
    transactionDate: "Дата",
    transactionNotes: "Заметка",
    transactionUpdateError: "Не удалось обновить расход",
    transactionDeleteError: "Не удалось удалить расход",
  },
  en: {
    brand: "Aura AI",
    secureAccess: "Secure access",
    heroTitle: "Smart life decisions begin with calm financial clarity.",
    heroBody:
      "Daily spending, savings goals and AI-generated advice in one elegant workspace built for thoughtful planning.",
    monthlyOverview: "Monthly overview",
    cashFlow: "AI-tracked cash flow",
    savingsStreak: "Savings streak",
    steadyProgress: "Steady progress, low stress",
    signupTitle: "Create your account",
    signupSubtitle:
      "Set up a secure workspace for your budgets, goals and future AI financial insights.",
    signupFooter: "Already have an account?",
    signIn: "Sign in",
    loginTitle: "Welcome back",
    loginSubtitle:
      "Log in to review your spending rhythm, progress on goals and AI-guided next steps.",
    loginFooter: "New to Aura AI?",
    createAccount: "Create an account",
    fullName: "Full name",
    email: "Email",
    password: "Password",
    passwordHint: "Minimum 8 characters",
    nameRequired: "Full name is required",
    nameMin: "Full name must be at least 2 characters",
    emailRequired: "Email is required",
    emailInvalid: "Email format is invalid",
    passwordRequired: "Password is required",
    passwordMin: "Password must be at least 8 characters",
    signupSuccess: "Account created. Your dashboard is ready.",
    signupError: "Could not create the account",
    signupCreating: "Creating account...",
    signupSubmit: "Create account",
    loginSuccess: "Welcome back. Session opened successfully.",
    loginError: "Login failed",
    loginCreating: "Signing in...",
    loginSubmit: "Sign in",
    dashboardTitle: "Aura AI Dashboard",
    dashboardGreeting: "Hi, {name}. Keep logging your spending and AI will watch the rest.",
    dashboardGreetingFallback: "friend",
    dashboardSubtitle:
      "Add expenses in plain language, create goals and follow trends in one interactive workspace.",
    refresh: "Refresh",
    logout: "Log out",
    dashboardLoadError: "Dashboard failed to load",
    insight: "Smart AI insight",
    insightLoading: "Insight is being prepared",
    insightBody:
      "Whenever the dashboard opens, AI analyzes your spending trends and shows a short note here.",
    totalIncome: "Total income",
    totalIncomeBody: "Combined total of all recorded income.",
    totalSpent: "Total spent",
    totalSpentBody: "Combined total of all recorded expenses",
    netBalance: "Net balance",
    netBalanceBody: "Difference between income and expenses",
    thisMonth: "This month",
    thisMonthBody: "Current month spending and overall momentum",
    activeGoals: "Active goals",
    activeGoalsBody: "Number of savings goals",
    expenseParser: "Expense parser",
    expenseParserTitle: "Just describe the expense",
    cashflowEntry: "Manual entry",
    cashflowEntryTitle: "Add income or expense quickly",
    cashflowEntryBody:
      "Record income in a green flow and save manual expenses in a structured format that stays easy to edit.",
    aiVisibility: "AI visibility",
    aiVisibilityTitle: "Every refresh brings a fresh signal",
    aiVisibilityBody:
      "When the dashboard reopens, AI generates a new signal based on recent expenses and goal progress.",
    currentSignal: "Current signal",
    aiCollecting: "AI is still gathering data.",
    spendingTrend: "Spending trend",
    spendingTrendTitle: "Last 7 days",
    spendingTrendEmpty: "Add at least one expense to see a trend",
    categoryMix: "Category mix",
    categoryMixTitle: "Where your money goes",
    categoryMixEmpty: "Categories will appear here after the AI parser runs",
    newGoal: "New goal",
    newGoalTitle: "Create a savings goal",
    goalTracker: "Goal tracker",
    goalTrackerTitle: "See what remains",
    goalRemaining: "Remaining: {amount}",
    saved: "Saved: {amount}",
    target: "Target: {amount}",
    noGoals: "No goals yet. Try adding one like \"Car fund 100,000,000\".",
    recentActivity: "Recent activity",
    recentActivityTitle: "Recent income and expenses",
    noTransactions: "Add your first income or expense above.",
    session: "Session",
    sessionTitle: "Current user",
    name: "Name",
    status: "Status",
    refreshing: "Dashboard is refreshing",
    workspace: "AI-connected workspace",
    goalRequired: "Goal title and target amount are required.",
    goalTargetPositive: "Target amount must be greater than 0.",
    goalCurrentPositive: "Current saved cannot be negative.",
    goalSuccess: "New goal added.",
    goalPlaceholder: "For example: Car savings",
    goalTargetPlaceholder: "Target amount",
    goalCurrentPlaceholder: "Current saved",
    goalSubmitting: "Saving...",
    goalSubmit: "Add goal",
    goalHint: "Choose whether you want to create a new goal or add money to an existing one.",
    createGoalMode: "New goal",
    contributeGoalMode: "Add to existing",
    selectGoal: "Select goal",
    contributeAmount: "Amount to add",
    contributeSubmit: "Add to goal",
    contributeSuccess: "Amount added to the goal.",
    goalSelectRequired: "Please select an existing goal first.",
    goalUpdateSuccess: "Goal updated.",
    goalDeleteSuccess: "Goal deleted.",
    goalUpdateError: "Could not update the goal",
    goalDeleteError: "Could not delete the goal",
    expenseEmpty: "Expense text cannot be empty.",
    expenseShort: "Please describe the expense in a little more detail.",
    expenseSuccess: "Expense saved successfully.",
    incomeSuccess: "Income saved successfully.",
    expensePlaceholder:
      "For example: I spent 65k on lunch today and then 18k on a taxi",
    expenseSubmitting: "AI is analyzing...",
    expenseSubmit: "Save expense",
    cashflowRequired: "Title, category and amount are required.",
    cashflowAmountPositive: "Amount must be greater than 0.",
    cashflowSubmitting: "Saving...",
    cashflowCreateError: "Could not save the income or expense",
    incomeMode: "Income",
    expenseMode: "Expense",
    incomeHint: "Track salary, bonus and freelance payments in a separate flow.",
    manualExpenseHint: "Manual expenses stay editable and instantly update the dashboard.",
    incomeTitlePlaceholder: "For example: Salary received",
    expenseTitlePlaceholder: "For example: Phone bill",
    incomeSubmit: "Save income",
    manualExpenseSubmit: "Add manual expense",
    edit: "Edit",
    delete: "Delete",
    cancel: "Cancel",
    save: "Save",
    deleteSuccess: "Expense deleted.",
    updateSuccess: "Expense updated.",
    incomeUpdateSuccess: "Income updated.",
    incomeDeleteSuccess: "Income deleted.",
    transactionTitle: "Title",
    transactionType: "Type",
    transactionCategory: "Category",
    transactionAmount: "Amount",
    transactionDate: "Date",
    transactionNotes: "Notes",
    transactionUpdateError: "Could not update the expense",
    transactionDeleteError: "Could not delete the expense",
  },
};

type Dictionary = (typeof dictionaries)["uz"];

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: keyof Dictionary, params?: Record<string, string | number>) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

function formatTemplate(value: string, params?: Record<string, string | number>) {
  if (!params) {
    return value;
  }
  return value.replace(/\{(\w+)\}/g, (_, key: string) => String(params[key] ?? ""));
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("uz");

  useEffect(() => {
    const stored = window.localStorage.getItem("aura-language") as Language | null;
    if (stored && LANGUAGES.includes(stored)) {
      setLanguage(stored);
    }
  }, []);

  useEffect(() => {
    window.localStorage.setItem("aura-language", language);
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => {
    const dictionary = dictionaries[language];
    return {
      language,
      setLanguage,
      t: (key, params) => formatTemplate(dictionary[key] ?? dictionaries.en[key], params),
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
